apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  PORT: "5000"
  REDIS_HOST: "redis-release-master"
  REDIS_PORT: "6379"
  IMPORTANT_ENV_VAR: {{ .Values.importantEnvValue }}
